export const data = [
    {
        id: 1,
        title: 'One',
        desc: 'This is GadgetsOne',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '1.2',
    },
    {
        id: 2,
        title: 'Two',
        desc: 'This is GadgetsTwo',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '0.5',
    },
    {
        id: 3,
        title: 'Three',
        desc: 'This is GadgetsThree',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '2.3',
    },
    {
        id: 4,
        title: 'Four',
        desc: 'This is GadgetsFour',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '1.4',
    },
    {
        id: 5,
        title: 'Five',
        desc: 'This is GadgetsFive',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '2.9',
    },
    {
        id: 6,
        title: 'Six',
        desc: 'This is GadgetsSix',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '5.9',
    },
    {
        id: 7,
        title: 'Seven',
        desc: 'This is GadgetsSeven',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '3.4',
    },
    {
        id: 8,
        title: 'Eight',
        desc: 'This is GadegtsEight',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '2.6',
    },
    {
        id: 9,
        title: 'Nine',
        desc: 'This is GadgetNine',
        image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
        price: '1.8',
    },
]